# lrc_generator/ass_formatter.py
from typing import List, Optional, Tuple

# Default ASS style for karaoke effect.
# Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, 
# Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, 
# BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
#
# - PrimaryColour: The color the text becomes *after* the karaoke sweep (highlighted color).
# - SecondaryColour: The color the text is *before* the karaoke sweep (base color).
# - Alignment: 2 is bottom center. 5 is middle center. 8 is top center.
#   (Numpad layout: 1-bottom-left, 2-bottom-center, 3-bottom-right, 4-mid-left, ..., 9-top-right)
# Alignment: 2 = bottom center
# MarginV: 30 = vertical margin from bottom (adjust as needed based on PlayResY)
# Encoding: 1 = System default, 0 = UTF-8. Let's use 0 for wider compatibility.
DEFAULT_STYLE = "Default,Arial,60,&H0000FFFF,&H00FFFFFF,&H00000000,&H60000000,0,0,0,0,100,100,0,0,1,2.5,1,5,10,10,10,0"

SCRIPT_INFO_TEMPLATE = """[Script Info]
; Script generated by LRC Word Transcriber
Title: {title}
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1024
PlayResY: 1024
ScaledBorderAndShadow: yes
Timer: 100.0000
;AISegmentInfo: Active Format,0
; Audio File: {audio_filename}
"""

DIALOGUE_FORMAT_LINE = "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"

def format_time_ass(seconds: float) -> str:
    """Converts seconds to ASS time format H:MM:SS.cc (centiseconds)."""
    if seconds < 0:
        seconds = 0
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    centiseconds = int(round((seconds - int(seconds)) * 100)) # round to nearest centisecond
    return f"{hours}:{minutes:02d}:{secs:02d}.{centiseconds:02d}"

class AssFormatter:
    def __init__(self, styles: Optional[List[str]] = None, 
                 default_video_width: int = 1024, 
                 default_video_height: int = 1024):
        """
        Initializes the AssFormatter.

        Args:
            styles: A list of ASS style strings. If None, uses DEFAULT_STYLE.
            default_video_width: Default video width for [Script Info] PlayResX.
            default_video_height: Default video height for [Script Info] PlayResY.
        """
        self.styles = styles if styles is not None else [DEFAULT_STYLE]
        self.video_width = default_video_width
        self.video_height = default_video_height

    def _generate_script_info_section(self, title: Optional[str] = None, audio_file: Optional[str] = None) -> List[str]:
        """Generates the [Script Info] section of the .ass file."""
        script_title = title if title else "Untitled Transcription"
        # Using the SCRIPT_INFO_TEMPLATE approach is more flexible if we keep it defined.
        # However, to match previous structure more directly for now:
        lines = [
            "[Script Info]",
            "; Script generated by LRC Word Transcriber",
            f"Title: {script_title}",
            "ScriptType: v4.00+",
            "WrapStyle: 0",
            f"PlayResX: {self.video_width}",
            f"PlayResY: {self.video_height}",
            "ScaledBorderAndShadow: yes",
            "Timer: 100.0000",
            ";AISegmentInfo: Active Format,0"
        ]
        if audio_file:
            lines.append(f"; Audio File: {audio_file}")
        lines.append("") # Empty line for separation
        return lines

    def _generate_styles_section(self) -> List[str]:
        """Generates the [V4+ Styles] section."""
        lines = [
            "[V4+ Styles]",
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"
        ]
        for style_definition in self.styles: # self.styles is usually [DEFAULT_STYLE]
            lines.append(f"Style: {style_definition}") # CRITICAL FIX: Prepend "Style: "
        lines.append("")
        return lines

    def _generate_events_section_header(self) -> List[str]:
        """Generates the header for the [Events] section."""
        return [
            "[Events]",
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
            "" # Restore empty line, it's harmless and common.
        ]

    def word_data_to_ass_events(self, word_level_timed_data: List[Tuple[str, float, float]], style_name: str = "Default") -> List[str]:
        """
        Converts word-level timed data to ASS dialogue events with karaoke effect.
        Original logic restored.
        Args:
            word_level_timed_data: List of (word_text, start_time_seconds, end_time_seconds).
            style_name: The name of the style to apply to these events.
        Returns:
            A list of strings, each representing an ASS Dialogue event line.
        """
        ass_events = []
        if not word_level_timed_data:
            return ass_events

        for i, (word, start_sec, end_sec) in enumerate(word_level_timed_data):
            if word is None or not word.strip() or start_sec is None or end_sec is None:
                continue
            
            if end_sec < start_sec:
                end_sec = start_sec + 0.01

            start_ass_time = format_time_ass(start_sec)
            end_ass_time = format_time_ass(end_sec)
            
            duration_centiseconds = max(0, int(round((end_sec - start_sec) * 100)))
            ass_text_content = word.replace('{', '\\{').replace('}', '\\}')
            karaoke_tagged_text = f"{{\\k{duration_centiseconds}}}{ass_text_content}"
            
            event_line = f"Dialogue: 0,{start_ass_time},{end_ass_time},{style_name},,0,0,0,,{karaoke_tagged_text}"
            ass_events.append(event_line)
            
        return ass_events

    def create_ass_file_content(self, 
                                word_level_timed_data: List[Tuple[str, float, float]], 
                                title: Optional[str] = None, 
                                audio_file_name: Optional[str] = None,
                                video_width: Optional[int] = None,
                                video_height: Optional[int] = None
                                ) -> str:
        """
        Generates the full content for an .ass subtitle file.

        Args:
            word_level_timed_data: List of (word, start_time_sec, end_time_sec).
            title: Optional title for the [Script Info] section.
            audio_file_name: Optional name of the audio file for comments.
            video_width: Optional video width to override instance default.
            video_height: Optional video height to override instance default.

        Returns:
            A string containing the complete .ass file content.
        """
        # Use provided video dimensions or instance defaults
        current_video_width = video_width if video_width is not None else self.video_width
        current_video_height = video_height if video_height is not None else self.video_height
        
        # Store original resolution to restore after this call if they were overridden
        original_width, original_height = self.video_width, self.video_height
        self.video_width = current_video_width
        self.video_height = current_video_height

        all_lines = []
        all_lines.extend(self._generate_script_info_section(title, audio_file_name))
        all_lines.extend(self._generate_styles_section())
        all_lines.extend(self._generate_events_section_header())
        
        # Assuming the first style in self.styles is the one to use for events,
        # or that 'Default' is always present and configured correctly.
        # For more robustness, could allow specifying style name for events.
        event_style_name = self.styles[0].split(',')[0] if self.styles else "Default"

        ass_events = self.word_data_to_ass_events(word_level_timed_data, style_name=event_style_name)
        all_lines.extend(ass_events)
        
        # Restore original default video dimensions
        self.video_width = original_width
        self.video_height = original_height
        
        return "\n".join(all_lines)

if __name__ == '__main__':
    # Example Usage (for testing this module directly)
    formatter = AssFormatter()

    # Sample word data (word, start_time_seconds, end_time_seconds)
    # This data would typically come from Whisper's word-level output
    sample_data = [
        ("Hello", 1.0, 1.8),
        ("world", 2.0, 2.5),
        ("this", 3.0, 3.3),
        ("is", 3.4, 3.6),
        ("a", 3.7, 3.8),
        ("test.", 4.0, 5.0)
    ]

    ass_content = formatter.create_ass_file_content(
        sample_data, 
        title="My Test Karaoke", 
        audio_file_name="test_song.mp3",
        video_width=1920,
        video_height=1080
    )
    
    print("=== Generated .ass File Content ===")
    print(ass_content)

    # To save to a file:
    # with open("test_karaoke.ass", "w", encoding="utf-8-sig") as f: # utf-8-sig for BOM
    #     f.write(ass_content)
    # print("\\nSaved to test_karaoke.ass") 