# lrc_generator/ass_formatter.py
from typing import List, Optional, Tuple
import re

# Default ASS style for karaoke effect.
# Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, 
# Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, 
# BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
#
# - PrimaryColour: The color the text becomes *after* the karaoke sweep (highlighted color).
# - SecondaryColour: The color the text is *before* the karaoke sweep (base color).
# - Alignment: 2 is bottom center. 5 is middle center. 8 is top center.
#   (Numpad layout: 1-bottom-left, 2-bottom-center, 3-bottom-right, 4-mid-left, ..., 9-top-right)
# - MarginV: 80 = vertical margin from bottom (pixels from bottom edge)
# - MarginL/MarginR: 10 = left/right margins (pixels from edges)
# Encoding: 1 = System default, 0 = UTF-8. Let's use 0 for wider compatibility.
#
# POSITION EXAMPLES:
# Bottom quarter (current): Alignment=2, MarginV=80
# Middle center: Alignment=5, MarginV=0  
# Top quarter: Alignment=8, MarginV=80
# Bottom left: Alignment=1, MarginV=80
DEFAULT_STYLE = "Default,Arial,60,&H0000FFFF,&H00FFFFFF,&H00000000,&H60000000,0,0,0,0,100,100,0,0,1,2.5,1,2,10,10,80,0"

SCRIPT_INFO_TEMPLATE = """[Script Info]
; Script generated by LRC Word Transcriber
Title: {title}
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1024
PlayResY: 1024
ScaledBorderAndShadow: yes
Timer: 100.0000
;AISegmentInfo: Active Format,0
; Audio File: {audio_filename}
"""

DIALOGUE_FORMAT_LINE = "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"

def format_time_ass(seconds: float) -> str:
    """Converts seconds to ASS time format H:MM:SS.cc (centiseconds)."""
    if seconds < 0:
        seconds = 0
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    centiseconds = int(round((seconds - int(seconds)) * 100)) # round to nearest centisecond
    return f"{hours}:{minutes:02d}:{secs:02d}.{centiseconds:02d}"

class AssFormatter:
    def __init__(self, styles: Optional[List[str]] = None, 
                 default_video_width: int = 1024, 
                 default_video_height: int = 1024,
                 sentence_mode: bool = False):
        """
        Initializes the AssFormatter.

        Args:
            styles: A list of ASS style strings. If None, uses DEFAULT_STYLE.
            default_video_width: Default video width for [Script Info] PlayResX.
            default_video_height: Default video height for [Script Info] PlayResY.
            sentence_mode: If True, generates sentence-based subtitles with word highlighting.
        """
        self.styles = styles if styles is not None else [DEFAULT_STYLE]
        self.video_width = default_video_width
        self.video_height = default_video_height
        self.sentence_mode = sentence_mode

    def _generate_script_info_section(self, title: Optional[str] = None, audio_file: Optional[str] = None) -> List[str]:
        """Generates the [Script Info] section of the .ass file."""
        script_title = title if title else "Untitled Transcription"
        # Using the SCRIPT_INFO_TEMPLATE approach is more flexible if we keep it defined.
        # However, to match previous structure more directly for now:
        lines = [
            "[Script Info]",
            "; Script generated by LRC Word Transcriber",
            f"Title: {script_title}",
            "ScriptType: v4.00+",
            "WrapStyle: 0",
            f"PlayResX: {self.video_width}",
            f"PlayResY: {self.video_height}",
            "ScaledBorderAndShadow: yes",
            "Timer: 100.0000",
            ";AISegmentInfo: Active Format,0"
        ]
        if audio_file:
            lines.append(f"; Audio File: {audio_file}")
        lines.append("") # Empty line for separation
        return lines

    def _generate_styles_section(self) -> List[str]:
        """Generates the [V4+ Styles] section."""
        lines = [
            "[V4+ Styles]",
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"
        ]
        for style_definition in self.styles: # self.styles is usually [DEFAULT_STYLE]
            lines.append(f"Style: {style_definition}") # CRITICAL FIX: Prepend "Style: "
        lines.append("")
        return lines

    def _generate_events_section_header(self) -> List[str]:
        """Generates the header for the [Events] section."""
        return [
            "[Events]",
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
            "" # Restore empty line, it's harmless and common.
        ]

    def _create_segment_karaoke_event(self, segment_words: List[Tuple[str, float, float]], style_name: str = "Default") -> str:
        """
        Creates a single ASS dialogue event for a segment with word-by-word highlighting.
        Only the currently singing word is highlighted, others remain normal.
        
        Args:
            segment_words: List of (word_text, start_time_seconds, end_time_seconds) for the segment.
            style_name: The name of the style to apply.
            
        Returns:
            A string representing an ASS Dialogue event line.
        """
        if not segment_words:
            return ""
        
        # Get overall timing for the segment
        segment_start = segment_words[0][1]
        segment_end = segment_words[-1][2]
        
        # Build the karaoke text with single-word highlighting
        karaoke_text_parts = []
        current_time = segment_start
        
        for i, (word, word_start, word_end) in enumerate(segment_words):
            # Calculate the gap before this word (if any)
            if word_start > current_time:
                gap_duration = word_start - current_time
                gap_centiseconds = max(0, int(round(gap_duration * 100)))
                if gap_centiseconds > 0:
                    # Add invisible karaoke tag for the gap
                    karaoke_text_parts.append(f"{{\\k{gap_centiseconds}}}")
            
            # Calculate duration for this word
            word_duration = word_end - word_start
            word_duration_centiseconds = max(10, int(round(word_duration * 100)))
            
            # Escape special characters
            escaped_word = word.replace('{', '\\{').replace('}', '\\}')
            
            # Add karaoke tag for this word - this creates the single-word highlight effect
            # The \k tag makes only this word highlighted during its duration
            karaoke_text_parts.append(f"{{\\k{word_duration_centiseconds}}}{escaped_word}")
            
            # Add space after word (except for last word or if word already ends with punctuation)
            if i < len(segment_words) - 1:
                # Check if we need a space
                current_word_stripped = word.rstrip()
                next_word = segment_words[i + 1][0].lstrip()
                
                # Add space if current word doesn't end with punctuation and next word doesn't start with punctuation
                if (not re.search(r'[.!?。！？,，;；:：]$', current_word_stripped) and 
                    not re.search(r'^[.!?。！？,，;；:：]', next_word)):
                    karaoke_text_parts.append(" ")
            
            # Update current time
            current_time = word_end
        
        # Combine all parts
        full_karaoke_text = "".join(karaoke_text_parts)
        
        # Format times
        start_ass_time = format_time_ass(segment_start)
        end_ass_time = format_time_ass(segment_end)
        
        # Create the dialogue line
        event_line = f"Dialogue: 0,{start_ass_time},{end_ass_time},{style_name},,0,0,0,,{full_karaoke_text}"
        
        return event_line

    def segments_to_ass_events(self, segment_data: List[List[Tuple[str, float, float]]], style_name: str = "Default") -> List[str]:
        """
        Converts segment-based data to ASS dialogue events with karaoke effect.
        Each segment appears as one line, with only the current word highlighted.
        
        Args:
            segment_data: List of segments, where each segment is a list of (word_text, start_time_seconds, end_time_seconds).
            style_name: The name of the style to apply to these events.
            
        Returns:
            A list of strings, each representing an ASS Dialogue event line for a segment.
        """
        ass_events = []
        if not segment_data:
            return ass_events
        
        # Create non-overlapping karaoke events for each segment
        for i, segment_words in enumerate(segment_data):
            if not segment_words:
                continue
                
            # Ensure segments don't overlap by adjusting timing if necessary
            segment_start = segment_words[0][1]
            segment_end = segment_words[-1][2]
            
            # If this is not the first segment, ensure there's a small gap
            if i > 0 and segment_data[i-1]:
                prev_segment_end = segment_data[i-1][-1][2]
                if segment_start < prev_segment_end + 0.1:  # 0.1 second minimum gap
                    # Adjust start time to avoid overlap
                    segment_start = prev_segment_end + 0.1
                    # Update the first word's start time
                    segment_words = [(segment_words[0][0], segment_start, segment_words[0][2])] + segment_words[1:]
            
            event_line = self._create_segment_karaoke_event(segment_words, style_name)
            if event_line:
                ass_events.append(event_line)
        
        return ass_events

    def create_ass_file_content_from_segments(self, 
                                            segment_data: List[List[Tuple[str, float, float]]], 
                                            title: Optional[str] = None, 
                                            audio_file_name: Optional[str] = None,
                                            video_width: Optional[int] = None,
                                            video_height: Optional[int] = None
                                            ) -> str:
        """
        Generates the full content for an .ass subtitle file using Whisper segments.

        Args:
            segment_data: List of segments, where each segment is a list of (word, start_time_sec, end_time_sec).
            title: Optional title for the [Script Info] section.
            audio_file_name: Optional name of the audio file for comments.
            video_width: Optional video width to override instance default.
            video_height: Optional video height to override instance default.

        Returns:
            A string containing the complete .ass file content.
        """
        # Use provided video dimensions or instance defaults
        current_video_width = video_width if video_width is not None else self.video_width
        current_video_height = video_height if video_height is not None else self.video_height
        
        # Store original resolution to restore after this call if they were overridden
        original_width, original_height = self.video_width, self.video_height
        self.video_width = current_video_width
        self.video_height = current_video_height

        all_lines = []
        all_lines.extend(self._generate_script_info_section(title, audio_file_name))
        all_lines.extend(self._generate_styles_section())
        all_lines.extend(self._generate_events_section_header())
        
        # Get the style name for events
        event_style_name = self.styles[0].split(',')[0] if self.styles else "Default"

        # Generate ASS events from segments
        if self.sentence_mode:
            ass_events = self.segments_to_ass_events(segment_data, style_name=event_style_name)
        else:
            # For word-by-word mode, flatten segments into individual words
            word_level_data = []
            for segment in segment_data:
                word_level_data.extend(segment)
            ass_events = self.word_data_to_ass_events(word_level_data, style_name=event_style_name)
        
        all_lines.extend(ass_events)
        
        # Restore original default video dimensions
        self.video_width = original_width
        self.video_height = original_height
        
        return "\n".join(all_lines)

    def word_data_to_ass_events(self, word_level_timed_data: List[Tuple[str, float, float]], style_name: str = "Default") -> List[str]:
        """
        Converts word-level timed data to ASS dialogue events with karaoke effect.
        
        Args:
            word_level_timed_data: List of (word_text, start_time_seconds, end_time_seconds).
            style_name: The name of the style to apply to these events.
        Returns:
            A list of strings, each representing an ASS Dialogue event line.
        """
        if self.sentence_mode:
            return self.sentence_data_to_ass_events(word_level_timed_data, style_name)
        
        # Original word-by-word implementation
        ass_events = []
        if not word_level_timed_data:
            return ass_events

        for i, (word, start_sec, end_sec) in enumerate(word_level_timed_data):
            if word is None or not word.strip() or start_sec is None or end_sec is None:
                continue
            
            if end_sec < start_sec:
                end_sec = start_sec + 0.01

            start_ass_time = format_time_ass(start_sec)
            end_ass_time = format_time_ass(end_sec)
            
            duration_centiseconds = max(0, int(round((end_sec - start_sec) * 100)))
            ass_text_content = word.replace('{', '\\{').replace('}', '\\}')
            karaoke_tagged_text = f"{{\\k{duration_centiseconds}}}{ass_text_content}"
            
            event_line = f"Dialogue: 0,{start_ass_time},{end_ass_time},{style_name},,0,0,0,,{karaoke_tagged_text}"
            ass_events.append(event_line)
            
        return ass_events

    def sentence_data_to_ass_events(self, word_level_timed_data: List[Tuple[str, float, float]], style_name: str = "Default") -> List[str]:
        """
        Converts word-level timed data to ASS dialogue events with sentence-based karaoke effect.
        Each sentence appears, highlights word by word, then disappears completely before the next sentence.
        
        Args:
            word_level_timed_data: List of (word_text, start_time_seconds, end_time_seconds).
            style_name: The name of the style to apply to these events.
            
        Returns:
            A list of strings, each representing an ASS Dialogue event line for a sentence.
        """
        ass_events = []
        if not word_level_timed_data:
            return ass_events
        
        # Group words into sentences
        sentences = self._group_words_into_sentences(word_level_timed_data)
        
        # Create non-overlapping karaoke events for each sentence
        for i, sentence_words in enumerate(sentences):
            if not sentence_words:
                continue
                
            # Ensure sentences don't overlap by adjusting timing if necessary
            sentence_start = sentence_words[0][1]
            sentence_end = sentence_words[-1][2]
            
            # If this is not the first sentence, ensure there's a small gap
            if i > 0 and sentences[i-1]:
                prev_sentence_end = sentences[i-1][-1][2]
                if sentence_start < prev_sentence_end + 0.1:  # 0.1 second minimum gap
                    # Adjust start time to avoid overlap
                    sentence_start = prev_sentence_end + 0.1
                    # Update the first word's start time
                    sentence_words = [(sentence_words[0][0], sentence_start, sentence_words[0][2])] + sentence_words[1:]
            
            event_line = self._create_sentence_karaoke_event(sentence_words, style_name)
            if event_line:
                ass_events.append(event_line)
        
        return ass_events

    def _group_words_into_sentences(self, word_level_timed_data: List[Tuple[str, float, float]]) -> List[List[Tuple[str, float, float]]]:
        """
        Groups words into sentences based on punctuation and timing gaps.
        
        Args:
            word_level_timed_data: List of (word_text, start_time_seconds, end_time_seconds).
            
        Returns:
            List of sentences, where each sentence is a list of word tuples.
        """
        if not word_level_timed_data:
            return []
        
        sentences = []
        current_sentence = []
        
        # Sentence-ending punctuation
        sentence_endings = {'.', '!', '?', '。', '！', '？'}
        # Additional punctuation that might indicate sentence breaks
        strong_breaks = {'.', '!', '?', '。', '！', '？', ':', '：'}
        
        for i, (word, start_time, end_time) in enumerate(word_level_timed_data):
            if word is None or not word.strip():
                continue
                
            current_sentence.append((word, start_time, end_time))
            
            # Check if this word ends a sentence
            word_stripped = word.strip()
            ends_sentence = False
            
            # Check for sentence-ending punctuation
            if any(punct in word_stripped for punct in sentence_endings):
                ends_sentence = True
            
            # Check for significant time gap to next word (indicating sentence break)
            if i < len(word_level_timed_data) - 1:
                next_word, next_start, _ = word_level_timed_data[i + 1]
                if next_word and next_word.strip():
                    time_gap = next_start - end_time
                    # Longer gap (1.5+ seconds) indicates sentence break
                    if time_gap > 1.5:
                        ends_sentence = True
                    # Medium gap (1+ seconds) with punctuation also indicates break
                    elif time_gap > 1.0 and any(punct in word_stripped for punct in strong_breaks):
                        ends_sentence = True
            
            # If this is the last word, end the sentence
            if i == len(word_level_timed_data) - 1:
                ends_sentence = True
            
            # Prevent sentences from being too long (max 15 words)
            if len(current_sentence) >= 15:
                ends_sentence = True
            
            if ends_sentence and current_sentence:
                sentences.append(current_sentence)
                current_sentence = []
        
        # Add any remaining words as a sentence
        if current_sentence:
            sentences.append(current_sentence)
        
        return sentences

    def _create_sentence_karaoke_event(self, sentence_words: List[Tuple[str, float, float]], style_name: str = "Default") -> str:
        """
        Creates a single ASS dialogue event for a sentence with word-by-word karaoke highlighting.
        The sentence appears, highlights word by word, then disappears completely.
        
        Args:
            sentence_words: List of (word_text, start_time_seconds, end_time_seconds) for the sentence.
            style_name: The name of the style to apply.
            
        Returns:
            A string representing an ASS Dialogue event line.
        """
        if not sentence_words:
            return ""
        
        # Get overall timing for the sentence
        sentence_start = sentence_words[0][1]
        sentence_end = sentence_words[-1][2]
        
        # Build the karaoke text with proper timing
        karaoke_text_parts = []
        current_time = sentence_start
        
        for i, (word, word_start, word_end) in enumerate(sentence_words):
            # Calculate the gap before this word (if any)
            if word_start > current_time:
                gap_duration = word_start - current_time
                gap_centiseconds = max(0, int(round(gap_duration * 100)))
                if gap_centiseconds > 0:
                    # Add invisible karaoke tag for the gap
                    karaoke_text_parts.append(f"{{\\k{gap_centiseconds}}}")
            
            # Calculate duration for this word
            word_duration = word_end - word_start
            word_duration_centiseconds = max(10, int(round(word_duration * 100)))
            
            # Escape special characters
            escaped_word = word.replace('{', '\\{').replace('}', '\\}')
            
            # Add karaoke tag for this word
            karaoke_text_parts.append(f"{{\\k{word_duration_centiseconds}}}{escaped_word}")
            
            # Add space after word (except for last word or if word already ends with punctuation)
            if i < len(sentence_words) - 1:
                # Check if we need a space
                current_word_stripped = word.rstrip()
                next_word = sentence_words[i + 1][0].lstrip()
                
                # Add space if current word doesn't end with punctuation and next word doesn't start with punctuation
                if (not re.search(r'[.!?。！？,，;；:：]$', current_word_stripped) and 
                    not re.search(r'^[.!?。！？,，;；:：]', next_word)):
                    karaoke_text_parts.append(" ")
            
            # Update current time
            current_time = word_end
        
        # Combine all parts
        full_karaoke_text = "".join(karaoke_text_parts)
        
        # Format times
        start_ass_time = format_time_ass(sentence_start)
        end_ass_time = format_time_ass(sentence_end)
        
        # Create the dialogue line
        event_line = f"Dialogue: 0,{start_ass_time},{end_ass_time},{style_name},,0,0,0,,{full_karaoke_text}"
        
        return event_line

if __name__ == '__main__':
    # Example Usage (for testing this module directly)
    formatter = AssFormatter()

    # Sample word data (word, start_time_seconds, end_time_seconds)
    # This data would typically come from Whisper's word-level output
    sample_data = [
        ("Hello", 1.0, 1.8),
        ("world", 2.0, 2.5),
        ("this", 3.0, 3.3),
        ("is", 3.4, 3.6),
        ("a", 3.7, 3.8),
        ("test.", 4.0, 5.0)
    ]

    ass_content = formatter.create_ass_file_content_from_segments(
        [sample_data], 
        title="My Test Karaoke", 
        audio_file_name="test_song.mp3",
        video_width=1920,
        video_height=1080
    )
    
    print("=== Generated .ass File Content ===")
    print(ass_content)

    # To save to a file:
    # with open("test_karaoke.ass", "w", encoding="utf-8-sig") as f: # utf-8-sig for BOM
    #     f.write(ass_content)
    # print("\\nSaved to test_karaoke.ass") 